---
title: "Lab 6: Dimension Reduction"
output:
  pagedown::html_paged:
    css: ["style/my-style-page.css", "default-fonts", "default-page", "default"]
    self_contained: true
    number_sections: true
---

We will use the `Hitters` data set in the `ISLR` package to predict `Salary` for baseball players.

```{r, message=FALSE}
library(ISLR)
library(tidyverse) 
library(knitr)

str(Hitters)
```

## Data Processing

1. Remove records with missing data. Create a new (complete) version of your data set. (Hint: `drop_na` in `tidyr` could be helpful.)
2. You may need to create dummy variables for categorical variables in your recipes. `step_dummy(all_nominal_predictors())` is a good way to do this.
3. You may need to standardize all variables in your recipes. `step_normalize(all_predictors())` is a good way to do this.


## Principal Components Regression

The function call `step_pca(all_predictors(), num_comp = d)` will compute $d$ principal components of predictors in a data frame as a component in a recipe.

1. Fit the PCR model using 10-fold cross validation for values of $M$. Be sure to normalize your predictors.
2. Create a plot of the CV MSE vs. $M$.
3. When does the smallest cross-validation error occur? Which $M$ would you choose for your final model?
5. How much variability in $Y$ is explained for your chosen value of $M$?

## Partial Least Squares

The function call `step_pls(all_predictors(), num_comp = d)` will compute $d$ partial least squares components of predictors in a data frame as a component in a recipe.

1. Fit the PLS model using 10-fold cross validation for values of $M$. Be sure to normalize your predictors.
2. Create a plot of the CV MSE vs. $M$.
3. When does the smallest cross-validation error occur? Which $M$ would you choose for your final model?
5. How much variability in $Y$ is explained for your chosen value of $M$?
5. Discuss the difference between PCR and PLS results. Which would you prefer?
