---
title: "Lab 6: Principal Components Regression and Partial Least Squares"
output:
  pagedown::html_paged:
    css: ["style/my-style-page.css", "default-fonts", "default-page", "default"]
    self_contained: true
    number_sections: true
---

We will continue to use the `Hitters` data set in the `ISLR` package to predict `Salary` for baseball players.

```{r, message=FALSE}
library(ISLR)
library(tidyverse) 
library(knitr)

str(Hitters)
```

## Data Processing

1. Remove records with missing values from the data (Hint: `complete.cases()` is useful)

## Principal Components Regression

The `pcr()` function in the `pls` package can perform principal components regression. 

1. Fit the PCR model using the `pcr` command. A couple tips: a) setting `scale = TRUE` will standardize your data prior to fitting the model, and b) setting `validation = TRUE` will perform 10-fold cross validation for each value of $M$.

2. Create a plot of the CV MSE (note root MSE is reported) vs. $M$.

3. When does the smallest cross-validation error occur? Which $M$ would you choose for your final model?

4. The `summary` function also provides the *percentage of variance explained* in the predictors and the response using $M$ principal components. How many principal components would we need to explain at least 80% of the variability in the predictors? 

5. How much variability in $Y$ is explained for your chosen value of $M$?

## Partial Least Squares

The `plsr()` function in the `pls` package can perform partial lest squares. 

1. Fit the PLS model using the `pls` command. Again, a) setting `scale = TRUE` will standardize your data prior to fitting the model, and b) setting `validation = TRUE` will perform 10-fold cross validation for each value of $M$.

2. Create a plot of the CV MSE (note root MSE is reported) vs. $M$.

3. When does the smallest cross-validation error occur? Which $M$ would you choose for your final model?

4. How much variability in $Y$ is explained for your chosen value of $M$?

5. Discuss the two methods performed today. Which would you prefer?
